### PR TITLE
Allow setting of last=0

### PR DESCRIPTION
**Pull request by dawnerd**
- Allow passed start/end can work
 - Grab all data if start/end not set

### CODE REVIEW

**Comment by dawnerd** [comment]
tests were failing before my change, FYI

**Comment by jgallen23** [comment]
This broke tests

**Comment by jgallen23** [comment]
We fixed tests earlier today and now failing again

**Comment by dawnerd** [comment]
Alright, will take a look

**Comment by dawnerd** [comment]
Looks like it's just timing out on one of them, passes locally but two take about a second each

**Pull request merged**
